### ISSUE TITLE
Where are multiple keysyms used?

### ISSUE THREAD

**Issue by pyfisch** [xkbcommon/libxkbcommon#136]
Libxkbcommon has both `xkb_state_key_get_one_sym` and `xkb_state_key_get_syms` to return one keysym or multiple keysyms for a keycode. For which keyboard layouts does libxkbcommon actually return multiple keysyms and is it important to handle them?

rust-windowing/winit#753 wants to improve keyboard events in this library, if each pressed keycode has just one associated keysym (and therefore only one Unicode codepoint) the code can be simpler as it only needs to store a single character vs. a variable length string.

**Comment by cheako** [comment]
I suppose the answer to this question could be found by scouring the Xorg source?  I would first check what libinput exposes.

**Comment by whot** [comment]
fwiw, libinput doesn't do XKB at all, it sits below XKB.

XKB originally was designed to have a N:1 translation between keycodes and keysyms, so one or more key strokes may produce one symbol. 1:N was not supported and is an addition to libxkbcommon only.

However, since everyone still uses xkeyboard-config layouts and they were all written for X you don't have any layouts yet that produce multiple keysyms.

**Comment by pyfisch** [comment]
Thank you @whot
