### ISSUE TITLE
1.3.0 tests fail on raspberry pi

### ISSUE THREAD

**Issue by kachanovskiy** [xkbcommon/libxkbcommon#244]
raspberry pi 3b+, with screen, no keyboard
Linux raspberrypi 5.10.33-v7+ #1415 SMP Fri Apr 30 15:49:00 BST 2021 armv7l GNU/Linux
gcc 11.1.0

build commands:
meson . _build --prefix=some_prefix -Denable-wayland=false -Denable-docs=false
ninja -C _build
ninja -C _build test

[xkbcommon-x11.test.log](https://github.com/xkbcommon/libxkbcommon/files/6419543/xkbcommon-x11.test.log)

**Comment by bluetech** [comment]
This probably happens because of what's mentioned in this comment:

https://github.com/xkbcommon/libxkbcommon/blob/b6aadd57d9ff6e9f59e174ec50a69e8d91f7e153/test/tool-option-parsing.py#L275-L277

We should improve this situation, but for now you can fix it by setting a prefix which contains the compose files (usually prefix `/usr` for the xlocaledir `/share/X11/locale`).

**Comment by kachanovskiy** [comment]
unfortunately, this does not seem to be a viable workaround for me...i'll have to wait for the fix.

thanks.

**Comment by bluetech** [comment]
Should be fixed in master.
