### ISSUE TITLE
 Add support for XDG_DATA_DIRS 

### ISSUE THREAD

**Issue by concatime** [xkbcommon/libxkbcommon#250]
Hi,
just lilke how Fontconfig [added support for `XDG_DATA_DIRS`](https://gitlab.freedesktop.org/fontconfig/fontconfig/-/commit/6f27f42e6140030715075aa3bd3e5cc9e2fdc6f1), can you add it to libxkbcommon too? It can be used to locate `xkb-config-root` and `x-locale-root` at runtime.
Note that, from [spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):
>  If $XDG_DATA_DIRS is either not set or empty, a value equal to /usr/local/share/:/usr/share/ should be used.

For now, the values of `xkb-config-root` and `x-locale-root` are hard-coded at compile-time.

Maye something like this ? :
```meson
xkeyboard_config_dep = dependency('xkeyboard-config', required: false)
[...]
if xkeyboard_config_dep.found()
  configh_data.set_quoted('DFLT_XKB_CONFIG_ROOT',
    xkeyboard_config_dep.get_pkgconfig_variable('xkb_base'))
endif
```

```c
	/* ... */
	/* if XDG_DATA_DIRS not empty, look into it */
#ifdef DFLT_XKB_CONFIG_ROOT
	/* try DFLT_XKB_CONFIG_ROOT */
#endif
	/* if XDG_DATA_DIRS empty, look into "/usr/local/share" and "/usr/share" */
```
I think you can drop the `xkb-config-root` options.

**Comment by whot** [comment]
the `xkeyboard-config` dependency is just for convenience, we don't actually need it. A distributions can just set `xkb-config-root` without going through pkgconfig and skip the xkeyboard-config dependency altogether. Dropping it may upset some distributions but I'd have to check who builds it with that value (Fedora uses pkgconfig because I'm lazy).

`XKB_CONFIG_ROOT` is also an environment variable that is parsed *and* there's `XKB_CONFIG_EXTRA_PATH` (defaulting to `/etc/xkb`). So I guess the main question is: what's the use-case you're trying to solve here?

**Comment by whot** [comment]
No reply, let's close it
