### ISSUE TITLE
rxkb_layout_get_description does not have i18n

### ISSUE THREAD

**Issue by tari01** [xkbcommon/libxkbcommon#293]
It seems that the strings read from `xkeyboard-config` are not being translated. I think they should be handled similarly to `libxklavier`. Please see the usage of `dgettext` and `XKB_DOMAIN` in https://github.com/freedesktop/libxklavier/blob/65c132a65e90a42e898f07243ef544109ada53c9/libxklavier/xklavier_config.c

**Comment by whot** [comment]
good point, I didn't think of that when I wrote this. Main question is now whether we leave this up to the caller or do it ourselves - @bluetech? From a quick peek at the xklavier file there are two components: the `dgettext()` call and the XML character conversion.

This code is from 2009, see http://bugs.freedesktop.org/21924. It looks like the code replaces `><&` in the XML file with their escaped characters, passes that to `dgettext()` and then does the same in reverse for the translated version (@svu may remember/confirm). But IMO the XML file containing unescaped characters is a bug in xkeyboard-config and we should treat it as such, so I reckon we can skip that escaping.

**Comment by whot** [comment]
Just for the record: libgnome-desktop does this already and always had, since it used to parse the XML itself, without libxklavier. See e.g. [gnome_xkb_info_description_for_option](https://gitlab.gnome.org/GNOME/gnome-desktop/-/blob/master/libgnome-desktop/gnome-xkb-info.c#L1010).

This means that if we add translations to the current API we potentially double-translate and may trigger bugs. That'd be an API change, so I reckon it may be better with a new API. I've filed #295 now as an inital attempt (took quite a while to figure out how to get the CI to pass...).

**Comment by tari01** [comment]
@whot 

Thank you for taking the time to look into this. Since https://github.com/xkbcommon/libxkbcommon/pull/295 is now dropped, I have switched to calling `dgettext` manualy in Ayatana. Closing.
