### ISSUE TITLE
Fn  seems to not be handled as a modifier on Wayland

### ISSUE THREAD

**Issue by djdeath** [xkbcommon/libxkbcommon#34]
Reported this issue on gnome-terminal under wayland :

https://bugzilla.gnome.org/show_bug.cgi?id=764825

Could it be related to xkbcommon?

**Comment by bluetech** [comment]
I am assuming you are not using some special custom keymap.

In the keyboards I know, `Fn` is usually a hardware modifier key, i.e. it doesn't reach the operating system at all. So I'll need some details on what happens when you press it:

If you can manage to compile xkbcommon (download the [latest release](http://xkbcommon.org/download/libxkbcommon-0.6.1.tar.xz), extract it, run `./configure && make check`), please show the output of these programs when you type the problematic sequence: `./test/interactive-evdev` and `./test/interactive-x11`.

If you don't manage, please use the command `xev` instead (in an X11 session, not Wayland).

**Comment by fooishbar** [comment]
@bluetech On Apple keyboards at least (this message comes to you from the Bluetooth one), pressing Fn does actually generate KEY_FN. The hardware does this because Fn's default state (i.e. Fn keys by default, or multimedia keys by default), can be determined by software. So the kernel does use this to compose the default presses, but then dutifully passes it through. Maybe the kernel should be squashing it instead?

Also, note that this only wasn't an issue on X11, because the keycode is 464 (472 with +8 shift), so couldn't be passed through there.

@djdeath Which keyboard are you using?

**Comment by bluetech** [comment]
@fooishbar If the keycode is 472, then xkeyboard-config at least doesn't map it to anything, and `xkb_state` calls trying to translate it to a keysym will fail. I wonder if a `GdkEventKey` is still generated in this case, and if so with what keysym ("keyval" in GDK).

Quickly tracing through the VTE code, if I'm reading correctly the scroll-on-keystroke check eventually relies on [this is-modifier test](https://github.com/GNOME/vte/blob/4b2a92a4a7a8014dd9bb4cb7a05a50aa2bd626a8/src/keymap.cc#L781) (see end of [this function](https://github.com/GNOME/vte/blob/4b2a92a4a7a8014dd9bb4cb7a05a50aa2bd626a8/src/vte.cc#L4824)).

**Comment by djdeath** [comment]
@fooishbar I'm using a Macbook Air, with UK layout.

**Comment by fooishbar** [comment]
I think @bluetech is right; the correct thing for GTK+ to do would be either to suppress key events it knows nothing about, or for VTE to not consider a zero-level key to be a non-modifier.
