### ISSUE TITLE
Increase PointerButton button id limit

### ISSUE THREAD

**Issue by labuwx** [xkbcommon/libxkbcommon#344]
Currently, the accepted button range for the PointerButton and LockPointerButton actions is 1..5.
My Logitech M720 mouse emulates a keyboard Ctrl+Alt+Tab when I press button 8. I would like to map that back to button 8.
Is it possible to increase the limit?

**Comment by wismill** [comment]
> I would like to map that back to button 8.

I am not sure I understand what you mean: in XKB you can _emulate_ pointer buttons, but you cannot map them.

The button emulation is currently limited to buttons 1 to 5. I think this is due to compatibility with the X11 core protocol.

[Solaar](https://github.com/pwr-Solaar/Solaar) may be a solution for remapping your mouse buttons.

**Comment by wismill** [comment]
Closing, as there is no feedback. Feel free to re-open if you have any new information.

**Comment by labuwx** [comment]
> [Solaar](https://github.com/pwr-Solaar/Solaar) may be a solution for remapping your mouse buttons.

Thanks. With Solaar I could remap the thumb button to a different key combination.
This solution is more elegant than what I wanted to hack together with XKB.
