### ISSUE TITLE
Can't input «angle quotes» into applications linked with libxkbcommon 1.5.0 running in GNOME linked with libxkbcommon 1.6.0

### ISSUE THREAD

**Issue by gentoo-root** [xkbcommon/libxkbcommon#435]
I run the latest Arch Linux with GNOME 45.3, it uses libxkbcommon 1.6.0. Some applications (installed with flatpak) use libxkbcommon 1.5.0 (flatpak's runtime is stuck with the old version). For example, these applications are Telegram (Qt) and Lutris (GTK). There is a runtime incompatibility between versions that doesn't allow me to type angle quotes `«»` into these applications.

Steps to reproduce:

0. Prepare the system according to the description above, i.e. install an application from flatpak, such as Telegram or Lutris.
1. Enable `misc:typo,lv3:ralt_switch` XKB options.
2. Open an application linked with libxkbcommon 1.5.0 (such as Telegram or Lutris) and put the cursor into any text field.
3. Try to type the angle quotes `«»` using RightAlt+< and RightAlt+>.
4. Nothing happens. Expected: angle quotes appear just as any other character.

References:

Telegram bug report: https://github.com/telegramdesktop/tdesktop/issues/26976
Flatpak bug report: https://github.com/flatpak/flatpak/issues/5585

**Comment by wismill** [comment]
Thank you for your report. This is due to _upstream_ [change in xorgproto](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/68): e.g. keysym `guillemotleft` has be deprecated in favor of `guillemetleft`.

What happen is:
- System xkbcommon 1.6 reads `guillemotleft` (_deprecated_) keysym from XKB database.
- Whenever an app asks for the keymap, it rewrites it to non-deprecated `guillemetleft`.
- But your app uses xkbcommon 1.5 that does not recognize `guillemetleft`, so you get nothing when typing it.

The immediate solution is to downgrade your _system_ `libxkbcommon`. The long term solution is to upgrade the `libxkcommon` used by the flatpak.

This is unfortunate but this is also a limitation of using flatpaks: you get libraries version incompatibilities.

**Comment by wismill** [comment]
@whot @bluetech how could we have a better handling of this situation? I now realize hat the author of the merge requests in `xorgproto` has done no impact assessment at all and there has been multiple issues related to keysym modifications; notably deleted dead keys in keyboard layout projects such as Neo and Bépo.

The fix would be to postpone the deprecation (by changing line order in the header) in order to let time to the apps to upgrade. The impact is not only limited to sandboxed apps: legacy X11 apps may be impacted if a distro did not upgrade X11  with libxkbcommon.

**Comment by whot** [comment]
Honestly, I think it's best to revert those patches in xorgproto. They were deprecated but still used (because there's nothing in place to *detect* use of deprected symbols) so removing them just broke things. Having those deprecated symbols doesn't really hurt in xorgproto, we'll spend more time debugging things like this than in total maintainer time spent on those symbols for the next decade...

**Comment by wismill** [comment]
@whot I agree. I opened an [MR for xorgproto](https://gitlab.freedesktop.org/xorg/proto/xorgproto/-/merge_requests/83).
