### ISSUE TITLE
meson.build script broke detection of --version-script support in GNU ld, as NetBSD uses

### ISSUE THREAD

**Issue by wismill** [xkbcommon/libxkbcommon#481]
_Originally posted by @glechapelain in https://github.com/xkbcommon/libxkbcommon/issues/459#issuecomment-2134184602:_

> I'll verify here but this seems to be causing grieves to pkgsrc using GNU: https://gnats.netbsd.org/cgi-bin/query-pr-single.pl?number=58272

Relevant PR: #459

**Comment by glechapelain** [comment]
Then it is what it is and the bug is not relevant ?
(And on Pkgsrc a toolchain of a certain degree is required to compile the sources from a certain revision?  I would expect that.

[We're at 2.39](http://cvsweb.netbsd.org/bsdweb.cgi/src/external/gpl3/binutils/dist/ld/ChangeLog?rev=1.11&content-type=text/x-cvsweb-markup&only_with_tag=MAIN))

**Comment by eli-schwartz** [comment]
Certainly it is a bug if libxkbcommon depends on linker options that only work with specific bleeding-edge versions of binutils.

I am surprised that the broken PR was ever merged, at least in the state it was in. This is an lld-specific issue, so it should have been gated on `cc.get_linker_id() == 'lld'`.
