### ISSUE TITLE
0.7.2 release build error

### ISSUE THREAD

**Issue by rezso** [xkbcommon/libxkbcommon#52]
If I try to compile the 0.7.2 release, I get this error:
https://gist.github.com/rezso/df5d227c044e03f6451ef2396dd2f84f
What's wrong?

**Comment by bluetech** [comment]
Thanks for the report.

I was able to reproduce this with meson 0.40.0 (the version you use), while it compiles fine with meson 0.41.0 (the version I started with) or meson 0.42.0 (the current version).

This is admittedly a very recent version, but I am tempted to just require >=0.41.0 rather than debug the issue. Do you have the option to upgrade meson?

If not, you can alternatively use the autotools build which is still in place (`./autogen.sh && ./configure && make`).

**Comment by rezso** [comment]
Thanks for your reply. With meson 0.42.0 I can compile the source.
I know, that the meson 0.40.0 is not the newest, but few months ago I downgraded from 0.41.2, because it causes build errors in budgie-desktop (see https://github.com/budgie-desktop/budgie-desktop/issues/1044).
But meson 0.42.0 is good for both libxkbcommon and budgie-desktop.
