### ISSUE TITLE
Consider documenting default configuration

### ISSUE THREAD

**Issue by oliviercailloux** [xkbcommon/libxkbcommon#532]
When creating my own configuration, it seems that some default configuration is in place even if my configuration files do not refer to it explicitly. For example,
```
default partial alphanumeric_keys modifier_keys
xkb_symbols "myconfig" {
  name[Group1]= "namegroup";
  include "latin"
};
```
[does not refer](https://gitlab.freedesktop.org/xkeyboard-config/xkeyboard-config/-/blob/master/symbols/latin) to the HOME key, but still the HOME key reacts as usual. In fact, even with “empty” config (removing `include "latin"`), the keyboard basically works.

Which defaults are taking place in such a case?

I would like to know because I am trying to achieve some behavior which I would like to copy from the default configuration (see [this question](https://unix.stackexchange.com/q/784974/)), but I guess that such information could be useful to users in general.

**Comment by wismill** [comment]
That's because of the *rules* mechanism. I suggest you start reading [this page](https://xkbcommon.org/doc/current/xkb-intro.html#md_doc_2introduction-to-xkb). Then if you want to know about the rules resolution, please read the [next version doc](https://xkbcommon.github.io/libxkbcommon/doc/current/rule-file-format.html), it's more complete.

The only default configuration is `evdev` for rules, `pc` for model and `us` for layout.
