### ISSUE TITLE
Question: How to create custom dead key and Compose entry?

### ISSUE THREAD

**Issue by Lieutenant-L-T-Smash** [xkbcommon/libxkbcommon#537]
Let's say I want a custom dead key that generates superscripts and another for subscripts. A "dead_superscript" and a "dead_subscript". These dead keys aren't available as pre-defined symbols, because their function is something new. (This is simplifying the problem and I know some predefined super/subscripts compositions are available, but the question is really about the generic case of how make a new dead key that does something interesting and doesn't collide with others.) 

My thought was that I could find an unused value in https://github.com/xkbcommon/libxkbcommon/blob/master/include/xkbcommon/xkbcommon-keysyms.h and simply use it as a direct hex val within my symbols and compose file. Without knowing which values may be "special", I tried a few, but with the same result.

In my symbols file (custom keyboard layout) I have:

`    key <AD02>	{ [         w,          W,   0x1140FFF0,       0xFE49 ]	};`

And in my Compose file I have:

```
<0x1140FFF0> <1>                 : "₁"   onesubscript # SUPERSCRIPT ONE
<0x1140FFF0> <2>                 : "₂"   twosubscript # SUPERSCRIPT TWO
<0x1140FFF0> <3>                 : "₃"   threesubscript # SUPERSCRIPT THREE
<0xFE49> <1>                   : "¹"   onesuperior # SUPERSCRIPT ONE
<0xFE49> <2>                   : "²"   twosuperior # SUPERSCRIPT TWO
<0xFE49> <3>                   : "³"   threesuperior # SUPERSCRIPT THREE
```

I expect that AltGR+W, then 1, will give me a subscript one. AltGR+Shift+W, then 1, will give a superscript one. The symbols file will generate a keysym with the hex value I selected (unless there are "forbidden" ones) and the Compose file will be used to match it. From what I read, this _should_ work, but it mostly doesn't. None of the native xfce apps seem to respect this, nor any other others I've tried. The odd exception is LibreOffice, which _does exactly what I expect_, which suggests that my idea is close but not quite right.

Is there something wrong with my approach? Is there a specific range of hex values I should use?  Is there a better way of doing this?

**Comment by wismill** [comment]
Your approach does work for apps/toolkits using libxkbcommon. The issue is probably that the apps where you Compose file does not work are not using it. Indeed, the Compose feature relies on an [*input method* (IM)](https://en.wikipedia.org/wiki/Input_method) and that requires some configuration; however every well designed distribution should come configured so the next explanation is whatever IM you use has an incomplete Compose support. I have seen this before: I fear this is yet another issue with Gtk or IBus.

But let’s take a dive:
0. First things first: do restarting your session fix the issue? Changes in Compose file require app/IM restart.
1. What is your setup (distro, version)? (DE is Xkfce)
2. What is the result of the following command: `ibus engine`?
3. What is the value of the following environment variable: `GTK_IM_MODULE`, `QT_IM_MODULE`, `XMODIFIERS`?
4. Does setting those variables to the following value in your `~/.profile` and restart your session fix the issue?
   ```
   GTK_IM_MODULE=xim
   QT_IM_MODULE=xim
   XMODIFIERS=@im=xim
   ```

---

By the way, do you know about [`xkbcli` tools](https://man.archlinux.org/man/xkbcli.1) for debugging?

**Comment by Lieutenant-L-T-Smash** [comment]
Thank you for helping. After a very long dive into this problem, ending with me reviewing GTK source code, I have a workaround. I'm omitting _a lot_ of what I learned to keep this simple, but suffice it to say there were moments of bewilderment and rage.

First, to answer your questions: (0) Yes, I'm restarting (1) It's a Devuan derivative (2) `ibus: command not found` (3) Empty for all (4) Mostly, but introduces a different problem.

You are right that the input method was the problem. With no method specified, GTK apps use a built-in IM called `gtk-im-context-simple`. It has a _hard-coded_ compose table as a default, which was very misleading early on as I assumed it must be reading one of the available Compose files on the system and I struggled to understand why it was ignoring my changes. 

Changing the IM to xim does indeed result in my Compose file changes being honoured. There is even a UI option to do this, in xfce4-settings-editor, in the xsettings channel, there is a Gtk/IMModule property. Setting this property to "xim" has the same effect as the env variable.

However, xim does not allow me to input arbitrary unicode characters using Ctrl+Shift+U, which is a feature of GTK's simple IM. I really didn't want to lose this feature. I looked into _why_ the simple IM wasn't reading my changes. One webpage said that it could _only_ use its hard-coded table. I believe that was outdated info, but it led me to the correct source file.

Most of the relevant logic is in https://gitlab.gnome.org/GNOME/gtk/-/blob/gtk-3-24/gtk/gtkcomposetable.c

As it turns out, the Compose sequence parser (`parse_compose_sequence`) will only accept pre-defined keysym names or Unicode code points. It simply will not parse raw hex values as I was trying. What's more, the IM only allows BMP code points (up to UFFFF). While the parser will add higher code points to the table, another function (`gtk_compose_list_check_uint16`) will _remove_ them. This was one of the (several) rage-inducing moments as I was investigating.

My solution is to make use of unassigned Unicode code points in the BMP. I have confirmed that surrogates (UD800-UDFFF) and noncharacters (UFDD0-UFDEF) work as dead keys. 

Thus, this works:

```<UDC03> <1>                      : "₁"   onesubscript # SUBSCRIPT ONE
<UDC03> <2>                        : "₂"   twosubscript # SUBSCRIPT TWO
<UDC03> <3>                        : "₃"   threesubscript # SUBSCRIPT THREE
<UDC03> <4>                        : "₄"   foursubscript # SUBSCRIPT FOUR
<UFDE1> <1>                        : "¹"   onesuperior # SUPERSCRIPT ONE
<UFDE1> <2>                        : "²"   twosuperior # SUPERSCRIPT TWO
<UFDE1> <3>                        : "³"   threesuperior # SUPERSCRIPT THREE
<UFDE1> <4>                        : "⁴"   foursuperior # SUPERSCRIPT FOUR```

This is more of a workaround than a proper solution. I really wanted to keep the Ctrl+Shift+U feature, and this allows it. Fortunately, this Compose strategy seems to work with every program I use, including non-GTK ones.

**Comment by wismill** [comment]
Great you could fix your issue!

> However, xim does not allow me to input arbitrary unicode characters using Ctrl+Shift+U, which is a feature of GTK's simple IM.

Neither does the Qt default IM, although this is the recommended method from the Unicode standard (ok, xim is excused). I am curious: what do you use it for? The main use I see for it for custom keyboard using QMK-like firmware. If you type regularly characters with `Ctrl+Shift+U`, wouldn’t be easier to create a custom keymap with those?

> As it turns out, the Compose sequence parser (`parse_compose_sequence`) will only accept pre-defined keysym names or Unicode code points. It simply will not parse raw hex values as I was trying. What's more, the IM only allows BMP code points (up to UFFFF). While the parser will add higher code points to the table, another function (`gtk_compose_list_check_uint16`) will _remove_ them. This was one of the (several) rage-inducing moments as I was investigating.

Yes, that’s what I feared. And this implementation has changed multiple times, so that’s why I wanted to know your config. Great investigation btw!

> My solution is to make use of unassigned Unicode code points in the BMP. I have confirmed that surrogates (UD800-UDFFF) and noncharacters (UFDD0-UFDEF) work as dead keys.

Yes, this is “standard” way. Some standard layouts use such trick and define the corresponding XCompose sequences. I think IBus added support for it recently too. Qt uses the xkbcommon implementation, so they have full Compose support.

**Comment by Lieutenant-L-T-Smash** [comment]
> I am curious: what do you use it for?

Testing and one-offs. Sometimes I'll want to see how some arbitrary unicode char looks or behaves. Of course it's better to map any chars that get frequent use. Being able to invoke that character to see if it might be useful is good. 

There are some that don't get used frequently enough to bother with, or would clutter up the mapping, but it's still nice to invoke them occasionally.

One can copy-and-paste them from elsewhere (I recommend symbl.cc for that) but I don't want to switch to a browser every time.
