### ISSUE TITLE
Caps Lock not disabled by "compose:caps" (or "caps:none") when "jp" in layout list

### ISSUE THREAD

**Issue by sulix** [xkbcommon/libxkbcommon#97]
When using "compose:caps" normally, the Caps Lock acts as a compose key, and no-longer acts as Caps Lock (it doesn't toggle caps-lock state, nor the LED). However, if "jp" is included in the layout list (even if it isn't the active layout), Caps Lock behaves as both Caps Lock and Compose.

For example, without "jp", the mods and leds are not changed by Caps Lock (here Multi_key as it's configured as Compose):
$ ./build/interactive-evdev -l us  -o compose:caps
keysyms [ Multi_key        ] unicode [  ] layout [ English (US) (0) ] level [ 0 ] mods [ ] leds [ ] 
keysyms [ apostrophe       ] unicode [ ' ] layout [ English (US) (0) ] level [ 0 ] mods [ ] leds [ ] 
keysyms [ e                ] unicode [ e ] layout [ English (US) (0) ] level [ 0 ] mods [ ] leds [ ] 

But, with "jp" in the list (even though it isn't the active layout), after Caps Lock (Multi_key) is pressed, mods and leds have been updated to show Lock and Caps Lock respectively (and the "E" is captialised:
$ ./build/interactive-evdev -l us,jp  -o compose:caps
keysyms [ Multi_key        ] unicode [  ] layout [ English (US) (0) ] level [ 0 ] mods [ ] leds [ ] 
keysyms [ apostrophe       ] unicode [ ' ] layout [ English (US) (0) ] level [ 0 ] mods [ Lock ] leds [ Caps Lock ] 
keysyms [ E                ] unicode [ E ] layout [ English (US) (0) ] level [ 1 ] mods [ -Lock ] leds [ Caps Lock ] 

(I was unable to get the -d option to 'interactive-evdev' working with my locale, so the Compose key isn't actually functioning in the above example, but the issue remains.)

This also affects the "caps:none" option, which should disable Caps Lock entirely, but while the keysym becomes VoidSymbol, Caps Lock's behaviour remains unchanged, as above.

This is running with libxkbcommon git (db7e79e78df07723dd07c8d00283244092dd8816), with the rules from xkeyboard-config-2.24. I've assumed that the fact that this is affecting a non-active layout makes this a libxkbcommon bug rather than an issue in xkeyboard-config, but I confess that it's just a guess — let me know if I'm mistaken and I'll re-file against xkeyboard-config.

I've also previously reported this issue to KDE:
https://bugs.kde.org/show_bug.cgi?id=408227

Thanks!

**Comment by bluetech** [comment]
I'll try to look into this during the weekend.

Meanwhile, it would be very helpful if you can reduce the bug as much as possible to a single `xkb` file. Basically, start with

```
./build/rmlvo-to-keymap --layout us,jp --options compose:caps --print > reproduce.xkb
```

Then remove stuff as much as possible while still being able to reproduce the issue with `interactive-evdev -k reproduce.xkb`.

**Comment by sulix** [comment]
Thanks!

I've reduced the reproducible case to https://davidgow.net/stuff/caps-compose-jp.xkb
It only supports three keys: 'e', apostrophe, and Caps_lock/Compose. This is sufficient to produce 'é' when running interactive-evdev with the -d option via <Compose>, e, '

The line that appears to be causing the problem is:
`modifier_map Lock { <CAPS> }`
It doesn't show up in the xkb file produced when --layout us is passed, and removing it from the xkb file fixes the issue.

The other obvious difference is in the `key <CAPS>` section inside `xkb_symbols`, which when the jp layout is included, also has a line
`symbols[Group2]= [ Eisu_toggle, Caps_Lock]`
Changing that line (to replace Caps_Lock with Multi_key — which is what it is for Group1 (presumably the us layout)) doesn't resolve the issue.

I guess the conceptual problem is that the "Lock" modifier is bound to the <CAPS> key, rather than the Caps_Lock symbol? I'm not sure if that's how modifiers (or xkb as a whole) works, though?

In any case, thanks, and let me know if there's anything else that'd be helpful!

Thanks!

**Comment by bluetech** [comment]
Thanks for reducing.

Let me explain what happens, it is a bit complex...

First, let's translate the RMLVO (the --layout and --options) to the lower level KCCGST (symbols, types, compat, etc, what XKB actually interprets):

```
$ ./build/rmlvo-to-kccgst -l us,jp -o compose:caps
keycodes: evdev+aliases(qwerty)
types:    complete
compat:   complete
symbols:  pc+us+jp:2+inet(evdev)+compose(caps)
```

From `compat: complete` (`test/data/compat/complete`) we get

```
default xkb_compatibility "complete" {
    include "basic"
    ....
};
```

which includes

```
xkb_compatibility {
    interpret Any+Lock {
	action= LockMods(modifiers=Lock);
    };
}
```

What this means is "If a key has exactly only the `Lock` modifier in its modifier map, make it lock the `Lock` modifier". The modifier map is a property of the entire key.

Further, `symbols: pc` eventually includes this statement

```
modifier_map Lock   { Caps_Lock };
```

what this means is "Go find the first key, ordered by (group, level, keycode), which has a `Caps_Lock` keysym, and add `Lock` to its modifier map". In the reducer, this keysym search procedure was already performed so it becomes

```
modifier_map Lock { <CAPS> };
```

Together, it means that even that `Caps_Lock` from the second level of the second group is enough to make the entire key lock `Lock`.

That's all well and good, but why doesn't the `compose:caps` option take care of it? Let's see how it's defined:

```
partial modifier_keys
xkb_symbols "caps" {                                                  
    key <CAPS> { type[Group1]="TWO_LEVEL", [ Multi_key, Multi_key ] };
}; 
```

and in `rules/evdev` the RMLVO is hooked up to the KCCGST like this:

```
! option       =      symbols
  compose:caps =      +compose(caps)
```

This rule only applies to the first group, so only the first group is modified, the jp group stays with the problematic `Caps_Lock` keysym. If you add a rule that would also match the second layout, it would work:

```
! layout[2]    option           =       symbols
  *            compose:caps     =       +compose(caps):2
```

Overall, things work as intended, just legacy/backward compat stuff end up with a bad outcome. If you are in a position to use a custom keymap, I can suggest some workarounds, otherwise I'd bring it up with xkeyboard-config and see if they have suggestions.
